name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Ganache
        run: npx ganache-cli -p 7545 -d > /dev/null &

      - name: Compile contracts
        run: npx truffle compile

      - name: Migrate contracts
        run: npx truffle migrate

      - name: Run tests
        run: npx truffle test